"""transactions api

Revision ID: 04c3c06e27ee
Revises: 52dec1186926
Create Date: 2025-09-21 01:19:23.792060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c3c06e27ee'
down_revision: Union[str, Sequence[str], None] = '52dec1186926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('provider', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'provider')
    # ### end Alembic commands ###
