"""add_full_name_company_name_to_user_kyc

Revision ID: 0ae911450b73
Revises: ef68f781f6df
Create Date: 2026-03-30 13:57:17.093768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae911450b73'
down_revision: Union[str, Sequence[str], None] = 'ef68f781f6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_kyc', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user_kyc', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_kyc', 'company_name')
    op.drop_column('user_kyc', 'full_name')
    # ### end Alembic commands ###
