"""add fxrates

Revision ID: 0e9db20197f4
Revises: 7de0ffa5fdf4
Create Date: 2025-11-11 15:00:45.675352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e9db20197f4'
down_revision: Union[str, Sequence[str], None] = '7de0ffa5fdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fxrates_id'), table_name='fxrates')
    op.drop_table('fxrates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fxrates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('buy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sell', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('buy_price', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sell_price', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fxrates_pkey'))
    )
    op.create_index(op.f('ix_fxrates_id'), 'fxrates', ['id'], unique=False)
    # ### end Alembic commands ###
