"""added user_id to transaction api

Revision ID: 0eb295240cd7
Revises: 545affb713b3
Create Date: 2025-09-23 16:18:26.460748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb295240cd7'
down_revision: Union[str, Sequence[str], None] = '545affb713b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('accounts_customer_id_fkey'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'customer_id')
    op.drop_constraint(op.f('transactions_customer_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('transactions_customer_id_fkey'), 'transactions', 'customer', ['customer_id'], ['id'])
    op.add_column('accounts', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('accounts_customer_id_fkey'), 'accounts', 'customer', ['customer_id'], ['id'])
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
