"""added user_id to transaction api

Revision ID: 29f197e7bf60
Revises: 04c3c06e27ee
Create Date: 2025-09-21 01:25:02.611382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f197e7bf60'
down_revision: Union[str, Sequence[str], None] = '04c3c06e27ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###
