"""add user foreign key to accounts

Revision ID: 45ac5b7064ca
Revises: f223f7a2ccce
Create Date: 2026-02-02 12:05:59.971236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ac5b7064ca'
down_revision: Union[str, Sequence[str], None] = 'f223f7a2ccce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user', sa.String(), nullable=False))
    op.create_foreign_key(None, 'accounts', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user')
    # ### end Alembic commands ###
