"""added balances and accountmetadata

Revision ID: 545affb713b3
Revises: 9c980548c8e1
Create Date: 2025-09-23 16:01:19.989985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545affb713b3'
down_revision: Union[str, Sequence[str], None] = '9c980548c8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balances', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('account_metadata', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_metadata')
    op.drop_column('accounts', 'balances')
    # ### end Alembic commands ###
