"""add_hidden_to_user_kyc

Revision ID: 634d9a99058e
Revises: 6274e9f9872b
Create Date: 2026-04-24 06:58:16.051026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634d9a99058e'
down_revision: Union[str, Sequence[str], None] = '6274e9f9872b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_kyc', sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_kyc', 'hidden')
    # ### end Alembic commands ###
