"""add fxrates.pair

Revision ID: 68cfd0613f3f
Revises: 0e9db20197f4
Create Date: 2025-11-11 15:16:14.214312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cfd0613f3f'
down_revision: Union[str, Sequence[str], None] = '0e9db20197f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fx_rates', sa.Column('pair', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fx_rates', 'pair')
    # ### end Alembic commands ###
