"""add user_kyc table

Revision ID: 6961ade1f979
Revises: ced4fe8e00cf
Create Date: 2026-03-18 15:45:52.116157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6961ade1f979'
down_revision: Union[str, Sequence[str], None] = 'ced4fe8e00cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_kyc', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_kyc', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('user_kyc', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_kyc', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_kyc', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_kyc', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_kyc', 'phone')
    op.drop_column('user_kyc', 'email')
    # ### end Alembic commands ###
