"""wallet and aml

Revision ID: 7a80c49e5b86
Revises: b7f9d1e42c10
Create Date: 2026-06-18 09:42:19.768843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a80c49e5b86'
down_revision: Union[str, Sequence[str], None] = 'b7f9d1e42c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_kyc', sa.Column('wallet', sa.String(), nullable=True))
    op.add_column('user_kyc', sa.Column('aml_document', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_kyc', 'aml_document')
    op.drop_column('user_kyc', 'wallet')
    # ### end Alembic commands ###
