"""create users table

Revision ID: 7de0ffa5fdf4
Revises: 0eb295240cd7
Create Date: 2025-10-04 11:23:54.951729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de0ffa5fdf4'
down_revision: Union[str, Sequence[str], None] = '0eb295240cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('admin_approved_by', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('admin_approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('success_callback_url', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('failed_callback_url', sa.String(), nullable=True))
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'source_account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'destination_rail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'destination_network',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'destination_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'payments', 'transactions', ['transaction_id'], ['id'])
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'description')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'destination_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'destination_network',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'destination_rail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'source_account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'failed_callback_url')
    op.drop_column('payments', 'success_callback_url')
    op.drop_column('payments', 'admin_approved_at')
    op.drop_column('payments', 'admin_approved_by')
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###
