"""add UBO forms

Revision ID: 84b4b81f6aa8
Revises: 6961ade1f979
Create Date: 2026-03-19 13:54:07.067141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b4b81f6aa8'
down_revision: Union[str, Sequence[str], None] = '6961ade1f979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_kyc_ubos', sa.Column('ownership_percentage', sa.Float(), nullable=True))
    op.alter_column('user_kyc_ubos', 'kyc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_kyc_ubos', 'ubo_reference_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_kyc_ubos', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_kyc_ubos', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_kyc_ubos', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_kyc_ubos', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_kyc_ubos', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_kyc_ubos', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_kyc_ubos', 'ubo_reference_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_kyc_ubos', 'kyc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_kyc_ubos', 'ownership_percentage')
    # ### end Alembic commands ###
