"""add user foreign key to accounts as nullable field

Revision ID: ced4fe8e00cf
Revises: 45ac5b7064ca
Create Date: 2026-02-02 12:09:02.931098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced4fe8e00cf'
down_revision: Union[str, Sequence[str], None] = '45ac5b7064ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user', sa.String(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user')
    # ### end Alembic commands ###
